server.port=${PORT:8080}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.mail.from=
app.mail.from-name=Sistema de Practicas UAH
app.frontend.url=http://localhost:5173

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dva9kgl4t}
cloudinary.api-key=${CLOUDINARY_API_KEY:387784988154869}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:CltJ5NlL1Dcr2PoMtDwK0UEhYZE}
