server.port=8082

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.mail.from=
app.mail.from-name=Sistema de Practicas UAH
app.frontend.url=http://localhost:5173

cloudinary.cloud-name=
cloudinary.api-key=
cloudinary.api-secret=
