server.port=8082

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dquejada1028@cue.edu.co
spring.mail.password=knfyhweeuoivawux
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.mail.from=dquejada1028@cue.edu.co
app.mail.from-name=Sistema de Prácticas UAH
app.frontend.url=http://localhost:5173

cloudinary.cloud-name=dr8idswdi
cloudinary.api-key=396878571375742
cloudinary.api-secret=_jAdyf3dM3ZYYCrwG1Y-xJfD9mY
