-- Vxx__seed_roles_faltantes.sql

INSERT INTO roles (nombre)
SELECT 'COORDINADOR_PRACTICA' WHERE NOT EXISTS (
    SELECT 1 FROM roles WHERE nombre = 'COORDINADOR_PRACTICA'
);

INSERT INTO roles (nombre)
SELECT 'SECRETARIA_COORDINACION' WHERE NOT EXISTS (
    SELECT 1 FROM roles WHERE nombre = 'SECRETARIA_COORDINACION'
);

INSERT INTO roles (nombre)
SELECT 'COORDINADOR_ACADEMICO' WHERE NOT EXISTS (
    SELECT 1 FROM roles WHERE nombre = 'COORDINADOR_ACADEMICO'
);

INSERT INTO roles (nombre)
SELECT 'TUTOR_EMPRESARIAL' WHERE NOT EXISTS (
    SELECT 1 FROM roles WHERE nombre = 'TUTOR_EMPRESARIAL'
);